### PR TITLE
Removed Redundant Dependencies, and Created A Count CSS Task

### PR DESCRIPTION
**Pull request by torch2424**
- Removed the dependencies `gulp-intercept` and `gulp-ext-rename`
- Created a task to count the number of characters in css with dist/ and output it's size in both number of characters, and bytes

cc @camelburrito are there any relevant issues for this? Also, let me know if this should be output to dist/ or src/ since I know you wanted to use this as a PR tool.

Example Output:

````
File name: core.css
Number of characters: 2139
Size: 2.139 KB
````

### CODE REVIEW

**Comment by camelburrito** [comment]
Can you checkin the size.txt?

**Comment by torch2424** [comment]
Also, I just included the filename in the output.

@camelburrito so you would like these files output in src on build then?

**Comment by camelburrito** [comment]
cc @erwinmombay

**Comment by camelburrito** [comment]
@torch2424 - This was not the requirement , lets sync on this tomorrow and finish this.

**Pull request merged**
