### PR TITLE
Fixing the closing body tag on www/index

### PR DESCRIPTION
**Pull request by camelburrito**
fixes https://github.com/ampproject/ampstart/issues/838

### CODE REVIEW

**Comment by camelburrito** [comment]
@erwinmombay - can you force push this , not sure why CLA keeps failing when i edit on GH

**Comment by torch2424** [comment]
@camelburrito Can you check your git config? Maybe it got weird somewhere, and your email is mismatched with the one you signed the CLA with?

**Comment by camelburrito** [comment]
@torch2424 -  i have Google CLA that i verified. I am able to merge stuff but not write code :)

**Comment by camelburrito** [comment]
I signed it!

**Pull request merged**
