### PR TITLE
Disable pointer on disabled buttons

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Changed `none`->`default`. This was actually a typo on my side and never intended. Sorry for the confusion. 

@derekcecillewis thanks for spotting this.

**Comment by camelburrito** [comment]
Agreed it should be default, i guess that is what @derekcecillewis has been trying to say (I was thinking none was the default :))

**Comment by camelburrito** [comment]
@sebastianbenz - i think your style should not be on :focus can you re do this?

**Comment by sebastianbenz** [comment]
@camelburrito Why is that? I thought disabled elements can't accept focus.

**Pull request merged**
