### PR TITLE
Use Google Analytics AMP Client ID API

### PR DESCRIPTION
**Pull request by sebastianbenz**
see https://support.google.com/analytics/answer/7486764

### CODE REVIEW

**Comment by camelburrito** [comment]
@sebastianbenz do you know if we still want this?

**Comment by sebastianbenz** [comment]
We still want this, but have to implement a cookie consent dialog first.

**Comment by ithinkihaveacat** [comment]
Is this necessary if the site is AMP Canonical?

> Google’s AMP Client ID API is a service that allows you to uniquely identify and analyze a user’s experience across AMP and non-AMP content.

Neither ampstart nor ampbyexample has any non-AMP content.

**Comment by camelburrito** [comment]
@ithinkihaveacat - I think it is to analyze user journeys across AMP sites and bring in more clarity in distinction among them

@sebastianbenz - I have already implemented a notifications dialog for AMP Start and we are not using it yet- https://github.com/ampproject/ampstart/tree/master/components/user-notification

**Comment by alankent** [comment]
HI @sebastianbenz - do you think this should be merged? I notice it's been sitting here for a few years... I am happy to review and approve.

**Pull request closed without merging**
